app:
  enemy-url: http://localhost:7414
  coordinator-url: http://localhost:8081
  team-name: Очень решительные слоны с синей спиной
  playground-id: 1
  self-addr: http://localhost:8080

spring:
  h2:
    console:
      enabled: true

spring.datasource.url: jdbc:h2:mem:battle_db
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect